<?php
namespace backend\controllers;

use common\components\keyStorage\FormModel;
use common\models\User;
use common\task\DownloadTask;
use Yii;
/**
 * Site controller
 */
class AdminController extends \yii\web\Controller
{
    public function init()
    {
        Yii::$app->language = 'vi';
        parent::init(); // TODO: Change the autogenerated stub
    }
}
